apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "todo-app.backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.DATABASE_URL | quote }}
  OPENAI_API_KEY: {{ .Values.secrets.OPENAI_API_KEY | quote }}
  JWT_SECRET_KEY: {{ .Values.secrets.JWT_SECRET_KEY | quote }}
  JWT_REFRESH_SECRET_KEY: {{ .Values.secrets.JWT_REFRESH_SECRET_KEY | quote }}
