{{- if .Values.dapr.enabled }}
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: reminder-cron
  namespace: {{ .Values.namespace }}
spec:
  type: bindings.cron
  version: v1
  metadata:
    - name: schedule
      value: "@every 5m"
    - name: route
      value: "/events/cron/check-reminders"
  scopes:
    - backend
{{- end }}
